name: flexcloud-stable
channels:
  - conda-forge
dependencies:
  # --- Build tools and a specific C++ compiler ---
  - cmake
  - make
  - gxx_linux-64=11.2

  # --- Pinning C++ libraries to known stable versions ---
  - boost #=1.74
  - pcl #=1.12
  - cgal #=5.4

  # --- Other project dependencies ---
  - python=3.9
  - pip
  - geographiclib
  - yaml-cpp
  - rerun-sdk
  - qt-main
  - pyqt